### ISSUE TITLE
[NPM Package] I have published my github action to the github marketplace.

### ISSUE THREAD

**Issue by mattzcarey** [mattzcarey/code-review-gpt#186]
Description:
will make it look much more pro

Validation:
screen shot

Tech steps:
https://docs.github.com/en/actions/creating-actions/publishing-actions-in-github-marketplace

**Comment by SEBRATHEZEBRA** [comment]
![Image](https://github.com/mattzcarey/code-review-gpt/assets/50981618/2662ddf1-09fb-4a0c-b074-589735f8187b)

**Comment by SEBRATHEZEBRA** [comment]
The action works in external repositories but only if you set the fetch-depth to 0 so that it fetches the whole commit history. It doesn't seem to work if you try set it to just the latest commit. Could be something to look into for the future

![Image](https://github.com/mattzcarey/code-review-gpt/assets/50981618/d13363be-e1c6-487c-92cf-6c6da1d65d44)
